### ISSUE TITLE
Strange glitch

### ISSUE THREAD

**Issue by legoboyvdlp** [FGMEMBERS/ATR72#1]
> Whenever I try to fly the ATR72-500(Omega Varient)
> The plane bounces into the sky as soon as I give it some throttle and let it roll 
> https://youtu.be/sv8U57DQXlw
> Can anybody fix this please thanks
> @Pakistan-1 
> I concur with Pakistan-1, only my version was straight off the Omega hangar (tried the other >version too, same broken physics). While accelerating on the ground, the craft suddenly >experiences (almost instantaneously?) a massive gain in speed. Direction wise, the speed gain >feels like directly up, forwards and sideways all at the same time. Doesn't seem to happen on >landing.
> Agough

And this gem by Mr Renk:

> Well, actually no - if you host something (in many cases despite the objection of the maintainer) >and allow everyone to edit this something (in many cases despite the objection of the >maintainer) - then you're responsible for what you host, modify and offer and can't offload that >at the feet of the original maintainer - this isn't how GPL works 

Checked, bug present.
@JWocky @FGDATA @IAHM-COL

**Comment by it0uchpods** [comment]
Hmm, I don't have that problem?

**Comment by it0uchpods** [comment]
Try to redownload the latest version, maybe something was broke? I'll have alook in a little bit.

**Comment by legoboyvdlp** [comment]
Just test it by starting up, increasing throttle. Just as well there isn't a virtual neck to be broken.

**Comment by legoboyvdlp** [comment]
And I'm just crossreporting from the forums

**Comment by legoboyvdlp** [comment]
Okay, flaps set, brakes set, full throttle. Releasing...
At about 40 knots, whip left, and begin to skid of runway.

**Comment by it0uchpods** [comment]
Hmm. I'll have a look.

**Comment by D-ECHO** [comment]
1. happens also to me
2. doesn't happen if you land first (start in the air)
3. also happens with the original version (https://bitbucket.org/muraleen/atr72-500-c-project/src)

**Comment by D-ECHO** [comment]
Any things you've found out, @it0uchpods ?

**Comment by D-ECHO** [comment]
Anyone else? @IAHM-COL @FGDATA @FGMEMBERS/fg-aircraftdevelopers ?
This bug really ruins the experience of this amazingly great aircraft.

**Comment by it0uchpods** [comment]
I do NOT have this issue.
2016.1.2

**Comment by D-ECHO** [comment]
Doesn't help... but I think it makes it a bit less hard

**Comment by paju1986** [comment]
Fixed.

**Comment by D-ECHO** [comment]
@paju1986 just tried and can confirm it works now! Thank you very much!
