### ISSUE TITLE
not working in FG 2020.3.18

### ISSUE THREAD

**Issue by mateusad** [FGMEMBERS/ATR72#3]
When I start Flightgear with this aircraft it only close the game when in initializing subsystems

**Comment by IAHM-COL** [comment]
![fgfs-20240114191253](https://github.com/FGMEMBERS/ATR72/assets/9952283/25d55832-a9c8-47f1-ab82-0d51fad85466)


It launches for me

**Comment by mateusad** [comment]
Oh my gosh

**Comment by mateusad** [comment]
Okay, I tried downloading by git clone, but no success. I am using windows, too.

**Comment by IAHM-COL** [comment]
How are you downloading. 
If you unpack the zip you have to rename the directory without -master
Regards

**Comment by mateusad** [comment]
Yes, i have downloaded in code>download zip, and clone with git.
And when I downloaded zip, i have renamed without -master.

**Comment by mateusad** [comment]
Some time after this issue, i managed to make this aircraft working.
I changed this lines in the instrumentation.xml file:
`<groundradar>
		<name>groundradar</name>
		<airport-id-source>instrumentation/groundradar/id</airport-id-source>
		
		
	</groundradar>`
to:
`<groundradar>
		<name>groundradar</name>
		<airport-id-source>instrumentation/groundradar/id</airport-id-source>
		<range-source>instrumentation/groundradar/range</range-source>
		<range-source>instrumentation/radar/range</range-source>
	</groundradar>`

**Comment by IAHM-COL** [comment]
ok, ill test it out

**Comment by IAHM-COL** [comment]
@mateusad 

https://github.com/FGMEMBERS/ATR72/commit/fb52610a8965a3d6e43d6d0dcf99d8d95a6f4f94

Implements your suggested fix
Please verify if this version is working, and we can close this issue

Thank you

**Comment by mateusad** [comment]
Working fine.
Thank you!
This aircraft is good made.
